# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialog_2d_post_processing.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_DialogPostProcessing2D(object):
    def setupUi(self, DialogPostProcessing2D):
        if not DialogPostProcessing2D.objectName():
            DialogPostProcessing2D.setObjectName(u"DialogPostProcessing2D")
        DialogPostProcessing2D.resize(900, 604)
        self.groupBoxPosition = QGroupBox(DialogPostProcessing2D)
        self.groupBoxPosition.setObjectName(u"groupBoxPosition")
        self.groupBoxPosition.setGeometry(QRect(20, 10, 171, 91))
        self.pushButtonGetMousePosition = QPushButton(self.groupBoxPosition)
        self.pushButtonGetMousePosition.setObjectName(u"pushButtonGetMousePosition")
        self.pushButtonGetMousePosition.setGeometry(QRect(10, 30, 61, 51))
        self.lineEditY = QLineEdit(self.groupBoxPosition)
        self.lineEditY.setObjectName(u"lineEditY")
        self.lineEditY.setGeometry(QRect(100, 60, 55, 25))
        self.labelXText = QLabel(self.groupBoxPosition)
        self.labelXText.setObjectName(u"labelXText")
        self.labelXText.setGeometry(QRect(80, 30, 16, 17))
        self.labelYText = QLabel(self.groupBoxPosition)
        self.labelYText.setObjectName(u"labelYText")
        self.labelYText.setGeometry(QRect(80, 60, 16, 17))
        self.lineEditX = QLineEdit(self.groupBoxPosition)
        self.lineEditX.setObjectName(u"lineEditX")
        self.lineEditX.setGeometry(QRect(100, 30, 55, 25))
        self.labelPlot = QLabel(DialogPostProcessing2D)
        self.labelPlot.setObjectName(u"labelPlot")
        self.labelPlot.setGeometry(QRect(380, 0, 500, 500))
        self.pushButtonPlot = QPushButton(DialogPostProcessing2D)
        self.pushButtonPlot.setObjectName(u"pushButtonPlot")
        self.pushButtonPlot.setGeometry(QRect(20, 180, 161, 41))
        self.groupBoxSavePlot = QGroupBox(DialogPostProcessing2D)
        self.groupBoxSavePlot.setObjectName(u"groupBoxSavePlot")
        self.groupBoxSavePlot.setGeometry(QRect(20, 240, 311, 101))
        self.pushButtonBrowseSavePlot = QPushButton(self.groupBoxSavePlot)
        self.pushButtonBrowseSavePlot.setObjectName(u"pushButtonBrowseSavePlot")
        self.pushButtonBrowseSavePlot.setGeometry(QRect(10, 60, 31, 31))
        self.pushButtonSavePlot = QPushButton(self.groupBoxSavePlot)
        self.pushButtonSavePlot.setObjectName(u"pushButtonSavePlot")
        self.pushButtonSavePlot.setGeometry(QRect(230, 60, 71, 31))
        self.lineEditFilePathSavePlot = QLineEdit(self.groupBoxSavePlot)
        self.lineEditFilePathSavePlot.setObjectName(u"lineEditFilePathSavePlot")
        self.lineEditFilePathSavePlot.setGeometry(QRect(40, 60, 181, 31))
        self.lineEditTime = QLineEdit(self.groupBoxSavePlot)
        self.lineEditTime.setObjectName(u"lineEditTime")
        self.lineEditTime.setGeometry(QRect(50, 30, 91, 21))
        self.labelTimeText = QLabel(self.groupBoxSavePlot)
        self.labelTimeText.setObjectName(u"labelTimeText")
        self.labelTimeText.setGeometry(QRect(10, 30, 41, 16))
        self.groupBoxExportAnimation = QGroupBox(DialogPostProcessing2D)
        self.groupBoxExportAnimation.setObjectName(u"groupBoxExportAnimation")
        self.groupBoxExportAnimation.setGeometry(QRect(20, 430, 311, 151))
        self.lineEditFilePathExportAnimation = QLineEdit(self.groupBoxExportAnimation)
        self.lineEditFilePathExportAnimation.setObjectName(u"lineEditFilePathExportAnimation")
        self.lineEditFilePathExportAnimation.setGeometry(QRect(40, 110, 181, 31))
        self.pushButtonBrowseExportAnimation = QPushButton(self.groupBoxExportAnimation)
        self.pushButtonBrowseExportAnimation.setObjectName(u"pushButtonBrowseExportAnimation")
        self.pushButtonBrowseExportAnimation.setGeometry(QRect(10, 110, 31, 31))
        self.pushButtonExportAnimation = QPushButton(self.groupBoxExportAnimation)
        self.pushButtonExportAnimation.setObjectName(u"pushButtonExportAnimation")
        self.pushButtonExportAnimation.setGeometry(QRect(230, 110, 71, 31))
        self.layoutWidget_2 = QWidget(self.groupBoxExportAnimation)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(10, 40, 291, 58))
        self.gridLayout = QGridLayout(self.layoutWidget_2)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.labelTimeIntervalText = QLabel(self.layoutWidget_2)
        self.labelTimeIntervalText.setObjectName(u"labelTimeIntervalText")

        self.gridLayout.addWidget(self.labelTimeIntervalText, 0, 0, 1, 1)

        self.lineEditTimeInterval = QLineEdit(self.layoutWidget_2)
        self.lineEditTimeInterval.setObjectName(u"lineEditTimeInterval")

        self.gridLayout.addWidget(self.lineEditTimeInterval, 0, 1, 1, 1)

        self.labelVideoFormatText = QLabel(self.layoutWidget_2)
        self.labelVideoFormatText.setObjectName(u"labelVideoFormatText")

        self.gridLayout.addWidget(self.labelVideoFormatText, 1, 0, 1, 1)

        self.comboBoxVideoFormat = QComboBox(self.layoutWidget_2)
        self.comboBoxVideoFormat.addItem("")
        self.comboBoxVideoFormat.addItem("")
        self.comboBoxVideoFormat.addItem("")
        self.comboBoxVideoFormat.setObjectName(u"comboBoxVideoFormat")

        self.gridLayout.addWidget(self.comboBoxVideoFormat, 1, 1, 1, 1)

        self.labelExportAnimationStatus = QLabel(self.groupBoxExportAnimation)
        self.labelExportAnimationStatus.setObjectName(u"labelExportAnimationStatus")
        self.labelExportAnimationStatus.setGeometry(QRect(10, 150, 67, 17))
        self.horizontalSliderTime = QSlider(DialogPostProcessing2D)
        self.horizontalSliderTime.setObjectName(u"horizontalSliderTime")
        self.horizontalSliderTime.setGeometry(QRect(350, 540, 541, 16))
        self.horizontalSliderTime.setOrientation(Qt.Horizontal)
        self.labelTimeText_2 = QLabel(DialogPostProcessing2D)
        self.labelTimeText_2.setObjectName(u"labelTimeText_2")
        self.labelTimeText_2.setGeometry(QRect(430, 560, 41, 21))
        self.labelTimeText_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.labelTime = QLabel(DialogPostProcessing2D)
        self.labelTime.setObjectName(u"labelTime")
        self.labelTime.setGeometry(QRect(470, 560, 41, 20))
        self.labelTime.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBoxSaveAllPLots = QGroupBox(DialogPostProcessing2D)
        self.groupBoxSaveAllPLots.setObjectName(u"groupBoxSaveAllPLots")
        self.groupBoxSaveAllPLots.setGeometry(QRect(20, 350, 311, 71))
        self.pushButtonBrowseSaveAllPlots = QPushButton(self.groupBoxSaveAllPLots)
        self.pushButtonBrowseSaveAllPlots.setObjectName(u"pushButtonBrowseSaveAllPlots")
        self.pushButtonBrowseSaveAllPlots.setGeometry(QRect(10, 30, 31, 31))
        self.lineEditFilePathSaveAllPlots = QLineEdit(self.groupBoxSaveAllPLots)
        self.lineEditFilePathSaveAllPlots.setObjectName(u"lineEditFilePathSaveAllPlots")
        self.lineEditFilePathSaveAllPlots.setGeometry(QRect(40, 30, 181, 31))
        self.pushButtonSaveAllPlots = QPushButton(self.groupBoxSaveAllPLots)
        self.pushButtonSaveAllPlots.setObjectName(u"pushButtonSaveAllPlots")
        self.pushButtonSaveAllPlots.setGeometry(QRect(230, 30, 71, 31))
        self.labelStatus = QLabel(DialogPostProcessing2D)
        self.labelStatus.setObjectName(u"labelStatus")
        self.labelStatus.setGeometry(QRect(580, 560, 301, 17))
        self.labelStatus.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.layoutWidget_3 = QWidget(DialogPostProcessing2D)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(20, 120, 161, 27))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.comboBoxAxis = QComboBox(self.layoutWidget_3)
        self.comboBoxAxis.addItem("")
        self.comboBoxAxis.addItem("")
        self.comboBoxAxis.setObjectName(u"comboBoxAxis")

        self.horizontalLayout.addWidget(self.comboBoxAxis)

        self.labelAxisText = QLabel(self.layoutWidget_3)
        self.labelAxisText.setObjectName(u"labelAxisText")
        self.labelAxisText.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout.addWidget(self.labelAxisText)

        self.layoutWidget_4 = QWidget(DialogPostProcessing2D)
        self.layoutWidget_4.setObjectName(u"layoutWidget_4")
        self.layoutWidget_4.setGeometry(QRect(20, 150, 161, 27))
        self.horizontalLayout_3 = QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.comboBoxPlotType = QComboBox(self.layoutWidget_4)
        self.comboBoxPlotType.addItem("")
        self.comboBoxPlotType.addItem("")
        self.comboBoxPlotType.setObjectName(u"comboBoxPlotType")

        self.horizontalLayout_3.addWidget(self.comboBoxPlotType)

        self.labelPlotTypeText = QLabel(self.layoutWidget_4)
        self.labelPlotTypeText.setObjectName(u"labelPlotTypeText")
        self.labelPlotTypeText.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.labelPlotTypeText)

        self.pushButtonPredictProperty = QPushButton(DialogPostProcessing2D)
        self.pushButtonPredictProperty.setObjectName(u"pushButtonPredictProperty")
        self.pushButtonPredictProperty.setGeometry(QRect(200, 140, 121, 51))
        self.pushButtonParticlesInfo = QPushButton(DialogPostProcessing2D)
        self.pushButtonParticlesInfo.setObjectName(u"pushButtonParticlesInfo")
        self.pushButtonParticlesInfo.setGeometry(QRect(200, 60, 121, 51))
        self.pushButtonLeft = QPushButton(DialogPostProcessing2D)
        self.pushButtonLeft.setObjectName(u"pushButtonLeft")
        self.pushButtonLeft.setGeometry(QRect(350, 560, 31, 25))
        self.pushButtonRight = QPushButton(DialogPostProcessing2D)
        self.pushButtonRight.setObjectName(u"pushButtonRight")
        self.pushButtonRight.setGeometry(QRect(390, 560, 31, 25))

        self.retranslateUi(DialogPostProcessing2D)

        QMetaObject.connectSlotsByName(DialogPostProcessing2D)
    # setupUi

    def retranslateUi(self, DialogPostProcessing2D):
        DialogPostProcessing2D.setWindowTitle(QCoreApplication.translate("DialogPostProcessing2D", u"Post Processing", None))
        self.groupBoxPosition.setTitle(QCoreApplication.translate("DialogPostProcessing2D", u"Select Postion", None))
        self.pushButtonGetMousePosition.setText("")
        self.lineEditY.setText(QCoreApplication.translate("DialogPostProcessing2D", u"0", None))
        self.labelXText.setText(QCoreApplication.translate("DialogPostProcessing2D", u"X", None))
        self.labelYText.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Y", None))
        self.lineEditX.setText(QCoreApplication.translate("DialogPostProcessing2D", u"0", None))
        self.labelPlot.setText("")
        self.pushButtonPlot.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Generate Plot", None))
        self.groupBoxSavePlot.setTitle(QCoreApplication.translate("DialogPostProcessing2D", u"Save Plot", None))
        self.pushButtonBrowseSavePlot.setText("")
        self.pushButtonSavePlot.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Export", None))
        self.lineEditTime.setText(QCoreApplication.translate("DialogPostProcessing2D", u"0.0", None))
        self.labelTimeText.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Time", None))
        self.groupBoxExportAnimation.setTitle(QCoreApplication.translate("DialogPostProcessing2D", u"Export Animation", None))
        self.pushButtonBrowseExportAnimation.setText("")
        self.pushButtonExportAnimation.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Export", None))
        self.labelTimeIntervalText.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Time interval(ms)", None))
        self.lineEditTimeInterval.setText(QCoreApplication.translate("DialogPostProcessing2D", u"200", None))
        self.labelVideoFormatText.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Video Format", None))
        self.comboBoxVideoFormat.setItemText(0, QCoreApplication.translate("DialogPostProcessing2D", u"mp4", None))
        self.comboBoxVideoFormat.setItemText(1, QCoreApplication.translate("DialogPostProcessing2D", u"mov", None))
        self.comboBoxVideoFormat.setItemText(2, QCoreApplication.translate("DialogPostProcessing2D", u"avi", None))

        self.labelExportAnimationStatus.setText("")
        self.labelTimeText_2.setText(QCoreApplication.translate("DialogPostProcessing2D", u"time:", None))
        self.labelTime.setText(QCoreApplication.translate("DialogPostProcessing2D", u"N/A", None))
        self.groupBoxSaveAllPLots.setTitle(QCoreApplication.translate("DialogPostProcessing2D", u"Save all plots", None))
        self.pushButtonBrowseSaveAllPlots.setText("")
        self.pushButtonSaveAllPlots.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Export", None))
        self.labelStatus.setText("")
        self.comboBoxAxis.setItemText(0, QCoreApplication.translate("DialogPostProcessing2D", u"x", None))
        self.comboBoxAxis.setItemText(1, QCoreApplication.translate("DialogPostProcessing2D", u"y", None))

        self.labelAxisText.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Axis", None))
        self.comboBoxPlotType.setItemText(0, QCoreApplication.translate("DialogPostProcessing2D", u"line", None))
        self.comboBoxPlotType.setItemText(1, QCoreApplication.translate("DialogPostProcessing2D", u"dotted", None))

        self.labelPlotTypeText.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Plot Type", None))
        self.pushButtonPredictProperty.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Predict \n"
"Property", None))
        self.pushButtonParticlesInfo.setText(QCoreApplication.translate("DialogPostProcessing2D", u"Paricles info.", None))
        self.pushButtonLeft.setText("")
        self.pushButtonRight.setText("")
    # retranslateUi

